# Generated by Django 5.0.2 on 2024-02-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0002_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=200)),
                ('b_name', models.CharField(max_length=200)),
                ('c_name', models.CharField(max_length=200)),
            ],
        ),
    ]
