# Generated by Django 5.0.2 on 2024-02-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0003_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1_name', models.CharField(max_length=200)),
                ('h2_name', models.CharField(max_length=200)),
            ],
        ),
    ]
