# Generated by Django 5.0.2 on 2024-02-24 09:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0004_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webtext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
