# Generated by Django 5.0.2 on 2024-02-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0006_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='img',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
    ]
