# Generated by Django 5.0.2 on 2024-02-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0008_alldestinationowl'),
    ]

    operations = [
        migrations.CreateModel(
            name='webimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image')),
            ],
        ),
    ]
