# Generated by Django 5.0.2 on 2024-02-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0009_webimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webimage',
            old_name='img',
            new_name='image',
        ),
    ]
