# Generated by Django 5.0.2 on 2024-02-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0010_rename_img_webimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='webimage',
            name='bg',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
    ]
