# Generated by Django 5.0.2 on 2024-02-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0012_alter_webimage_bg_alter_webimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webimage',
            name='bg',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='webimage',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
