# Generated by Django 5.0.2 on 2024-02-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0013_alter_webimage_bg_alter_webimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='latestdesti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='image')),
            ],
        ),
    ]
