# Generated by Django 5.0.2 on 2024-02-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0018_webtext_des1'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1_name', models.CharField(max_length=200)),
            ],
        ),
    ]
