# Generated by Django 5.0.2 on 2024-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0019_webbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='h5_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
