# Generated by Django 5.0.2 on 2024-02-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0022_headline_h6_name_webbutton_b2_name_webtext_des2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='image')),
            ],
        ),
    ]
