# Generated by Django 5.0.2 on 2024-02-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0023_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='h7_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
