# Generated by Django 5.0.2 on 2024-02-26 05:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0024_headline_h7_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtext',
            name='des3',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
