# Generated by Django 5.0.2 on 2024-02-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0025_webtext_des3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lastpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L_name', models.CharField(max_length=200)),
                ('l1_name', models.CharField(max_length=200)),
                ('l2_name', models.CharField(max_length=200)),
                ('l3_name', models.CharField(max_length=200)),
            ],
        ),
    ]
