# Generated by Django 5.0.2 on 2024-02-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0026_lastpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastpageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1_name', models.CharField(max_length=200)),
                ('l2_name', models.CharField(max_length=200)),
                ('l3_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='lastpage',
            name='l1_name',
        ),
        migrations.RemoveField(
            model_name='lastpage',
            name='l2_name',
        ),
        migrations.RemoveField(
            model_name='lastpage',
            name='l3_name',
        ),
    ]
