# Generated by Django 5.0.2 on 2024-02-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0027_lastpagecontent_remove_lastpage_l1_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastpage',
            old_name='L_name',
            new_name='L1_name',
        ),
        migrations.AddField(
            model_name='lastpage',
            name='L2_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lastpage',
            name='L3_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
