# Generated by Django 5.0.2 on 2024-02-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0028_rename_l_name_lastpage_l1_name_lastpage_l2_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lastpage',
        ),
        migrations.DeleteModel(
            name='LastpageContent',
        ),
    ]
