# Generated by Django 5.0.2 on 2024-02-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0029_delete_lastpage_delete_lastpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lastpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L1_name', models.CharField(max_length=200)),
            ],
        ),
    ]
