# Generated by Django 5.0.2 on 2024-02-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0030_lastpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='lastpageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1_name', models.CharField(max_length=200)),
            ],
        ),
    ]
