# Generated by Django 5.0.2 on 2024-02-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0032_lastpage_l2_name_lastpage_l3_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webimage',
            name='tep',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
    ]
