# Generated by Django 5.0.2 on 2024-02-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0034_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateogry',
            name='c1_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cateogry',
            name='c2_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cateogry',
            name='c3_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
