# Generated by Django 5.0.2 on 2024-02-29 09:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0035_cateogry_c1_name_cateogry_c2_name_cateogry_c3_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogdesti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image')),
                ('a', models.CharField(max_length=200)),
                ('des', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
