# Generated by Django 5.0.2 on 2024-03-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0036_blogdesti'),
    ]

    operations = [
        migrations.AddField(
            model_name='webimage',
            name='ser',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
    ]
