# Generated by Django 5.0.2 on 2024-03-08 09:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapage', '0040_aboutwho'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutwho',
            name='b',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutwho',
            name='des1',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
